/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether the database answers within a second. */
    get: operations['healthz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description The server's health. */
    Health: {
      /** @description Always `ok`: a server that cannot answer sends a problem. */
      status: components['schemas']['HealthStatus'];
    };
    /**
     * @description The status of a healthy server.
     * @enum {string}
     */
    HealthStatus: 'ok';
    /**
     * @description An error, as RFC 9457 problem details with a stable code and its parameters, never a
     *     sentence: the interface translates `errors.<code>`.
     * @example {
     *       "code": "quota.storage_exceeded",
     *       "params": {
     *         "limit": 100000000,
     *         "requested": 2000000,
     *         "used": 99000000
     *       },
     *       "status": 409,
     *       "type": "urn:life-pixel:problem:quota.storage_exceeded"
     *     }
     */
    Problem: {
      /** @description The stable code, dot-separated `snake_case` segments, domain first. */
      code: string;
      /** @description The parameters of the code's message, with camelCase keys. */
      params: {
        [key: string]: unknown;
      };
      /**
       * Format: int32
       * @description The HTTP status.
       */
      status: number;
      /** @description `urn:life-pixel:problem:<code>`. */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The database answers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description The database does not answer: `service.unavailable` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
