/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in account, with its storage usage and quota. */
    get: operations['getAccount'];
    put?: never;
    post?: never;
    /** Deletes the signed-in account, its library and its sessions, and clears the session cookie. */
    delete: operations['deleteAccount'];
    options?: never;
    head?: never;
    /** Sets the language of the signed-in account's emails and interface. */
    patch: operations['updateAccount'];
    trace?: never;
  };
  '/api/v1/account/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The signed-in account's data: a zip laid out like a local library — the desktop app opens it
     *     once unzipped —, plus `account.json` with its address, language, plan and sign-up date.
     */
    get: operations['exportAccount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/animations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * A page of the account's animations, from the most recently updated: those of a project,
     *     those whose title holds a text, or all.
     */
    get: operations['listAnimations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/animations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The animation `id`, without its document. */
    get: operations['getAnimation'];
    put?: never;
    post?: never;
    /** Deletes the animation `id`, whatever the quota. */
    delete: operations['deleteAnimation'];
    options?: never;
    head?: never;
    /**
     * Retitles the animation `id` — a save of its document, under `If-Match` —, moves it to
     *     another project, or both.
     */
    patch: operations['updateAnimation'];
    trace?: never;
  };
  '/api/v1/animations/{id}/document': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The document of the animation `id`. */
    get: operations['getDocument'];
    /** Replaces the document of the animation `id`, when `If-Match` names its current version. */
    put: operations['saveDocument'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/animations/{id}/duplicate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Copies the animation `id` under a new title, into another project or beside the original. */
    post: operations['duplicateAnimation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Replaces the signed-in account's password, and ends its other sessions. */
    put: operations['changePassword'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Emails a link setting a new password, when an active account has the address. The answer is
     *     the same, and as quick, whether it has or not.
     */
    post: operations['requestPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password-reset/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sets a new password with the token of an emailed link, and ends every session of the account. */
    post: operations['confirmPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The session the request carries, and its CSRF token. */
    get: operations['getSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Opens a session with an address and its password. */
    post: operations['signIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session the request carries, if any, and clears its cookie. */
    post: operations['signOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates an account, signs it in, and sends the email that verifies its address. */
    post: operations['signUp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verifies the address of the account an emailed link was sent to, and spends its token. */
    post: operations['verifyEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify-email/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sends the signed-in account's verification email again, with a new link; nothing once the
     *     address is verified.
     */
    post: operations['resendVerificationEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Records an allowed product event; the subject comes from the session when there is one. Once
     *     the request parses, this never fails: a full channel only drops the event, counted by
     *     `events_dropped_total`.
     */
    post: operations['createEvent'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A page of the account's projects, from the most recently updated. */
    get: operations['listProjects'];
    put?: never;
    /** Creates an empty project. */
    post: operations['createProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The project `id`. */
    get: operations['getProject'];
    put?: never;
    post?: never;
    /** Deletes the project `id` and its animations, whatever the quota. */
    delete: operations['deleteProject'];
    options?: never;
    head?: never;
    /** Renames the project `id`. */
    patch: operations['renameProject'];
    trace?: never;
  };
  '/api/v1/projects/{id}/animations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates an animation in the project `id` from its document: the app's first save. */
    post: operations['createAnimation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/projects/{id}/duplicate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Copies the project `id` and its animations into a new project; the whole copy is checked
     *     against the quota first.
     */
    post: operations['duplicateProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether the database answers within a second. */
    get: operations['healthz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description An account as its owner sees it. */
    Account: {
      /**
       * Format: date-time
       * @description When it signed up.
       */
      createdAt: string;
      /** @description Its address, as it signed up with it. */
      email: string;
      /** @description Whether the address is verified. */
      emailVerified: boolean;
      /**
       * Format: uuid
       * @description Its id.
       */
      id: string;
      /** @description The language code of its emails and interface. */
      language: string;
      /** @description Its plan: `free`. */
      plan: string;
      /** @description Its documents' bytes and its quota. */
      storage: components['schemas']['Storage'];
    };
    /** @description A change of the account: its language. */
    AccountChange: {
      /** @description The language code of its emails and interface, one of `languages.json`. */
      language: string;
    };
    /** @description The confirmation of a deletion. */
    AccountDeletionRequest: {
      /** @description The account's password, asked again. */
      password: string;
    };
    /**
     * Format: binary
     * @description A data export: a zip laid out like a local library, plus `account.json`.
     */
    AccountExport: string;
    /** @description An animation of the account's library, without its document. */
    Animation: {
      /**
       * Format: date-time
       * @description When it was created.
       */
      createdAt: string;
      /**
       * Format: int64
       * @description The size of its document, in bytes: what it counts against the quota.
       */
      documentBytes: number;
      /**
       * Format: int32
       * @description Its frames.
       */
      frameCount: number;
      /**
       * Format: int32
       * @description The canvas height, in pixels.
       */
      height: number;
      /**
       * Format: uuid
       * @description Its id.
       */
      id: string;
      /**
       * Format: uuid
       * @description The project holding it.
       */
      projectId: string;
      /** @description Its title. */
      title: string;
      /**
       * Format: date-time
       * @description When its document last changed, or it moved.
       */
      updatedAt: string;
      /**
       * Format: int64
       * @description Its version: the `ETag` of its document, which a write names in `If-Match`.
       */
      version: number;
      /**
       * Format: int32
       * @description The canvas width, in pixels.
       */
      width: number;
    };
    /** @description A change of an animation: its title — a save, under `If-Match` —, its project, or both. */
    AnimationChange: {
      /**
       * Format: uuid
       * @description The project to move it to.
       */
      projectId?: string | null;
      /** @description The new title. */
      title?: string | null;
    };
    /** @description A copy of an animation. */
    AnimationCopy: {
      /**
       * Format: uuid
       * @description The project of the copy; the original's when absent.
       */
      projectId?: string | null;
      /** @description The copy's title. */
      title: string;
    };
    /** @description A document, as the model serializes it: the format of the local library's files. */
    AnimationDocument: Record<string, never>;
    /**
     * @description The one name the app's allow-list accepts today (`docs/v1/server.md`, H13); any other value
     *     fails to deserialize, and answers `request.malformed`.
     * @enum {string}
     */
    EventName: 'export_completed';
    /** @description A product event the app reports, with the browsing context every one of them carries. */
    EventRequest: {
      appVersion: string;
      language: string;
      name: components['schemas']['EventName'];
      platform: string;
      properties: components['schemas']['ExportCompletedProperties'];
    };
    /** @description `export_completed`'s properties: the format downloaded and its raw, uncompressed size. */
    ExportCompletedProperties: {
      /** Format: int64 */
      bytes: number;
      format: components['schemas']['ExportFormat'];
    };
    /**
     * @description The format a completed export used, as `docs/v1/service.md` fixes the list.
     * @enum {string}
     */
    ExportFormat: 'wasm' | 'gif' | 'apng' | 'sprite_sheet' | 'png_frames';
    /** @description The server's health. */
    Health: {
      /** @description Always `ok`: a server that cannot answer sends a problem. */
      status: components['schemas']['HealthStatus'];
    };
    /**
     * @description The status of a healthy server.
     * @enum {string}
     */
    HealthStatus: 'ok';
    /** @description A page of a list, from the most recently updated item. */
    Page_Animation: {
      /** @description The items. */
      items: {
        /**
         * Format: date-time
         * @description When it was created.
         */
        createdAt: string;
        /**
         * Format: int64
         * @description The size of its document, in bytes: what it counts against the quota.
         */
        documentBytes: number;
        /**
         * Format: int32
         * @description Its frames.
         */
        frameCount: number;
        /**
         * Format: int32
         * @description The canvas height, in pixels.
         */
        height: number;
        /**
         * Format: uuid
         * @description Its id.
         */
        id: string;
        /**
         * Format: uuid
         * @description The project holding it.
         */
        projectId: string;
        /** @description Its title. */
        title: string;
        /**
         * Format: date-time
         * @description When its document last changed, or it moved.
         */
        updatedAt: string;
        /**
         * Format: int64
         * @description Its version: the `ETag` of its document, which a write names in `If-Match`.
         */
        version: number;
        /**
         * Format: int32
         * @description The canvas width, in pixels.
         */
        width: number;
      }[];
      /** @description The `cursor` of the next page; `null` on the last one. */
      nextCursor?: string | null;
    };
    /** @description A page of a list, from the most recently updated item. */
    Page_Project: {
      /** @description The items. */
      items: {
        /**
         * Format: int32
         * @description How many animations it holds.
         */
        animationCount: number;
        /**
         * Format: date-time
         * @description When it was created.
         */
        createdAt: string;
        /**
         * Format: uuid
         * @description Its id.
         */
        id: string;
        /** @description Its name. */
        name: string;
        /**
         * Format: date-time
         * @description When it or one of its animations last changed.
         */
        updatedAt: string;
      }[];
      /** @description The `cursor` of the next page; `null` on the last one. */
      nextCursor?: string | null;
    };
    /** @description A change of password. */
    PasswordChangeRequest: {
      /** @description The current password. */
      currentPassword: string;
      /** @description The new password: 12 to 128 characters. */
      newPassword: string;
    };
    /** @description A new password, with the token of the emailed link. */
    PasswordResetConfirmation: {
      /** @description The new password: 12 to 128 characters. */
      password: string;
      /** @description The link's `token`. */
      token: string;
    };
    /** @description A request for a link setting a new password. */
    PasswordResetRequest: {
      /** @description The account's address. */
      email: string;
    };
    /**
     * @description An error, as RFC 9457 problem details with a stable code and its parameters, never a
     *     sentence: the interface translates `errors.<code>`.
     * @example {
     *       "code": "quota.storage_exceeded",
     *       "params": {
     *         "limit": 100000000,
     *         "requested": 2000000,
     *         "used": 99000000
     *       },
     *       "status": 409,
     *       "type": "urn:life-pixel:problem:quota.storage_exceeded"
     *     }
     */
    Problem: {
      /** @description The stable code, dot-separated `snake_case` segments, domain first. */
      code: string;
      /** @description The parameters of the code's message, with camelCase keys. */
      params: {
        [key: string]: unknown;
      };
      /**
       * Format: int32
       * @description The HTTP status.
       */
      status: number;
      /** @description `urn:life-pixel:problem:<code>`. */
      type: string;
    };
    /** @description A project of the account's library. */
    Project: {
      /**
       * Format: int32
       * @description How many animations it holds.
       */
      animationCount: number;
      /**
       * Format: date-time
       * @description When it was created.
       */
      createdAt: string;
      /**
       * Format: uuid
       * @description Its id.
       */
      id: string;
      /** @description Its name. */
      name: string;
      /**
       * Format: date-time
       * @description When it or one of its animations last changed.
       */
      updatedAt: string;
    };
    /** @description A project's name: to create, rename or duplicate it. */
    ProjectName: {
      /** @description The name. */
      name: string;
    };
    /** @description A session: the account signed in, and the token its unsafe requests send in `X-CSRF-Token`. */
    Session: {
      /** @description The account signed in. */
      account: components['schemas']['Account'];
      /** @description The CSRF token of the session. */
      csrfToken: string;
    };
    /** @description A sign-in. */
    SignInRequest: {
      /** @description The address, whatever its case. */
      email: string;
      /** @description The password. */
      password: string;
    };
    /** @description A sign-up. */
    SignUpRequest: {
      /** @description The address; spaces around it are ignored. */
      email: string;
      /** @description The language code of the interface, one of `languages.json`. */
      language: string;
      /** @description The password: 12 to 128 characters. */
      password: string;
    };
    /** @description An account's storage. */
    Storage: {
      /**
       * Format: int64
       * @description Its quota, in bytes.
       */
      limitBytes?: number | null;
      /**
       * Format: int64
       * @description The bytes of its documents.
       */
      usedBytes: number;
    };
    /** @description The token of an emailed verification link. */
    VerifyEmailRequest: {
      /** @description The link's `token`. */
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The account */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  deleteAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountDeletionRequest'];
      };
    };
    responses: {
      /** @description The account is deleted: `Set-Cookie` clears the session cookie */
      204: {
        headers: {
          /** @description The cleared session cookie */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.current_password`, `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountChange'];
      };
    };
    responses: {
      /** @description The account, changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Account'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `account.language` (`available`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  exportAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The zip, as an attachment named `life-pixel-export-<YYYY-MM-DD>.zip` */
      200: {
        headers: {
          /** @description The file's name */
          'Content-Disposition'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/zip': components['schemas']['AccountExport'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listAnimations: {
    parameters: {
      query?: {
        /** @description Only the animations of this project. */
        project?: string;
        /** @description Only the animations whose title holds this text, whatever its case. */
        q?: string;
        /** @description The `nextCursor` of the previous page; none for the first. */
        cursor?: string;
        /** @description The most items of the page: 1 to 100, 50 by default. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of the animations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_Animation'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getAnimation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The animation's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The animation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Animation'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.animation_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  deleteAnimation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The animation's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The animation is deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.animation_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateAnimation: {
    parameters: {
      query?: never;
      header?: {
        /** @description `"<version>"`, with a title */
        'If-Match'?: string | null;
      };
      path: {
        /** @description The animation's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AnimationChange'];
      };
    };
    responses: {
      /** @description The animation, changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Animation'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.animation_not_found`, `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `quota.storage_exceeded` (`used`, `limit`, `requested`); deleting always works */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.version_conflict` (`current`): the document changed since */
      412: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.name` (`max`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.version_required`: `If-Match` names the version replaced */
      428: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The animation's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The document; `ETag` is its version */
      200: {
        headers: {
          /** @description `"<version>"` */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/vnd.life-pixel.animation+json': components['schemas']['AnimationDocument'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.animation_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  saveDocument: {
    parameters: {
      query?: never;
      header: {
        /** @description `"<version>"`: the version replaced */
        'If-Match': string;
      };
      path: {
        /** @description The animation's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/vnd.life-pixel.animation+json': components['schemas']['AnimationDocument'];
      };
    };
    responses: {
      /** @description The animation, saved; `ETag` is its new version */
      200: {
        headers: {
          /** @description `"<version>"` */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Animation'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.animation_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `quota.storage_exceeded` (`used`, `limit`, `requested`); deleting always works */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.version_conflict` (`current`): the document changed since */
      412: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.too_large` (`maxBytes`) */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `request.unsupported_media_type`: not `application/vnd.life-pixel.animation+json` */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description A `document.*` code of the model, with its parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.version_required`: `If-Match` names the version replaced */
      428: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  duplicateAnimation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The animation's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AnimationCopy'];
      };
    };
    responses: {
      /** @description The copy */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Animation'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.animation_not_found`, `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `quota.storage_exceeded` (`used`, `limit`, `requested`); deleting always works */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.name` (`max`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeRequest'];
      };
    };
    responses: {
      /** @description The password is changed; the other sessions ended */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `auth.unauthenticated` */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.current_password`, `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.password_length` (`min`, `max`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 5 a minute per account, as signing in */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description A link is on its way, if an account has the address */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 5 an hour per address and per email */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  confirmPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirmation'];
      };
    };
    responses: {
      /** @description The password is set; every session has ended */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `auth.token_invalid`: unknown, used or expired */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.password_length` (`min`, `max`); the token still works */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The session */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInRequest'];
      };
    };
    responses: {
      /** @description Signed in: `Set-Cookie` holds the session */
      200: {
        headers: {
          /** @description The session cookie */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      /** @description `auth.invalid_credentials`: an unknown address or a wrong password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 10 a minute per address, 5 per address signed in to */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  signOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out: `Set-Cookie` clears the session cookie */
      204: {
        headers: {
          /** @description The cleared session cookie */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpRequest'];
      };
    };
    responses: {
      /** @description The account, signed in: `Set-Cookie` holds its session */
      201: {
        headers: {
          /** @description The session cookie */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      /** @description `auth.csrf`: from another origin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.email_taken` */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.email_invalid`, `auth.password_length` (`min`, `max`), `account.language` (`available`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 5 an hour per address */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailRequest'];
      };
    };
    responses: {
      /** @description The address is verified */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `auth.token_invalid`: unknown, used or expired */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  resendVerificationEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The email is on its way, if the address is unverified */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `auth.unauthenticated` */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 3 an hour per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  createEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EventRequest'];
      };
    };
    responses: {
      /** @description Recorded, or silently dropped under load */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a name, property or value outside the allow-list */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 60 a minute per address */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listProjects: {
    parameters: {
      query?: {
        /** @description The `nextCursor` of the previous page; none for the first. */
        cursor?: string;
        /** @description The most items of the page: 1 to 100, 50 by default. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of the projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_Project'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectName'];
      };
    };
    responses: {
      /** @description The project */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.name` (`max`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The project and its animations are deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  renameProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectName'];
      };
    };
    responses: {
      /** @description The project, renamed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.name` (`max`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  createAnimation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/vnd.life-pixel.animation+json': components['schemas']['AnimationDocument'];
      };
    };
    responses: {
      /** @description The animation; `ETag` is its version */
      201: {
        headers: {
          /** @description `"<version>"` */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Animation'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `quota.storage_exceeded` (`used`, `limit`, `requested`); deleting always works */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.too_large` (`maxBytes`) */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `request.unsupported_media_type`: not `application/vnd.life-pixel.animation+json` */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description A `document.*` code of the model, with its parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  duplicateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectName'];
      };
    };
    responses: {
      /** @description The copy */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.unauthenticated`: no session, or one that ended */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `auth.account_suspended`, `auth.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `library.project_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `quota.storage_exceeded` (`used`, `limit`, `requested`); deleting always works */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `document.name` (`max`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 600 a minute per account */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The database answers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description The database does not answer: `service.unavailable` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
