// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

// The size and complexity limits of AGENTS.md.
const sizeRules = {
  'max-lines': ['error', 400],
  'max-lines-per-function': ['error', { max: 30, skipBlankLines: true, skipComments: true }],
};
const complexityRules = {
  'max-params': ['error', 3],
  'max-depth': ['error', 3],
  complexity: ['error', 10],
};

// Imports kept out of production files. A file's `no-restricted-imports` replaces the one of an
// earlier block, so each block below lists every restriction that applies to its files.
const engineTestingImports = {
  group: ['**/engine/testing', '**/engine/testing/*'],
  message: 'engine/testing is test code: import EDITOR_ENGINE or EngineStore instead.',
};
const httpImports = {
  group: ['@angular/common/http', '@angular/common/http/*'],
  message:
    'ApiClient (shared/src/lib/api) is the only user of HttpClient: add a service beside it.',
};
const restrictedImports = (...patterns) => ({
  'no-restricted-imports': ['error', { patterns }],
});
// The files allowed to use @angular/common/http (server.md, H3): the API client and its
// services, the app's providers, and the i18n loaders, which fetch static catalogues and legal
// pages, not the API.
const httpUsers = [
  'projects/shared/src/lib/api/**',
  'projects/app/src/app/app.config.ts',
  'projects/shared/src/lib/i18n/available-languages.ts',
  'projects/shared/src/lib/i18n/catalogue-loader.ts',
  'projects/app/src/app/legal/legal-text-loader.ts',
];

module.exports = defineConfig([
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      ...sizeRules,
      ...complexityRules,
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'lp', style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'lp', style: 'kebab-case' },
      ],
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
    },
  },
  {
    // Generated by `npm run api:generate` and `cargo xtask build-editor`: never edited, never
    // linted.
    ignores: [
      'projects/shared/src/lib/api/schema.d.ts',
      'projects/app/src/app/engine/wasm/generated/**',
    ],
  },
  {
    // engine/testing/ is test code (editor.md, W0): production files get the engine through
    // EDITOR_ENGINE and EngineStore, never the mock directly. The unit tests' build swaps
    // default-engine.ts for testing/default-engine.ts instead (angular.json, `mock-engine`).
    files: ['**/*.ts'],
    ignores: ['**/*.spec.ts', '**/engine/testing/**'],
    rules: restrictedImports(engineTestingImports, httpImports),
  },
  {
    files: httpUsers,
    ignores: ['**/*.spec.ts'],
    rules: restrictedImports(engineTestingImports),
  },
  {
    files: ['**/engine/testing/**/*.ts'],
    ignores: ['**/*.spec.ts'],
    rules: restrictedImports(httpImports),
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {
      '@angular-eslint/template/prefer-control-flow': 'error',
    },
  },
  {
    files: ['tools/**/*.mjs'],
    extends: [eslint.configs.recommended],
    languageOptions: {
      sourceType: 'module',
      globals: { console: 'readonly', process: 'readonly', URL: 'readonly' },
    },
    rules: { ...sizeRules, ...complexityRules },
  },
  {
    // engine-contract.ts defines the shared suite as nested `describe`/`it` blocks: like a spec
    // file, its size is the suite's, not a single function's.
    files: [
      '**/*.spec.ts',
      'e2e/**/*.ts',
      'tools/**/*.test.mjs',
      '**/engine/testing/engine-contract.ts',
    ],
    rules: { 'max-lines': 'off', 'max-lines-per-function': 'off' },
  },
]);
