/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/v1/alerts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The firing alerts of an environment. */
    get: operations['getAlerts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/audit-log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * A page of the audit log, newest first: the entries of `adminId`, of `action`, about
     *     `targetId`.
     */
    get: operations['listAuditLog'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The live session. */
    get: operations['getSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Opens a session: `Set-Cookie: __Host-lpa_session`, and the session. A wrong address,
     *     password or code is `admin.invalid_credentials`, whichever it is.
     */
    post: operations['signIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ends the session, if any, and clears its cookie. */
    post: operations['signOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/links/grafana': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A Grafana Explore link to a request's logs and trace. */
    get: operations['getGrafanaLink'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The newest log lines of an environment. */
    get: operations['getLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/metrics/product': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The product metrics from `from` to `to`: sign-ups, activation, active accounts, exports, MCP
     *     calls and storage, then the open requests by status and the medians of their age, of the time
     *     to a first answer and of the time to resolution.
     */
    get: operations['getProductMetrics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/monitoring/overview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Is everything fine? The tiles of an environment. */
    get: operations['getOverview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/monitoring/series': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A panel's series, and the previous period's. */
    get: operations['getPanelSeries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/support-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * A page of the queue, from the most recently updated request: each with its account's address
     *     and its age.
     */
    get: operations['listSupportRequests'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/support-requests/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The request `id`: its context and every message, the team's internal notes included. */
    get: operations['getSupportRequest'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Changes the status or the assignee of the request `id`, at least one of them. Only a new
     *     status moves its `updatedAt`.
     */
    patch: operations['updateSupportRequest'];
    trace?: never;
  };
  '/api/admin/v1/support-requests/{id}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Adds a message of the team to the request `id`. A reply moves the request to
     *     `waiting_for_user`, records the first response, and is emailed to the person as
     *     `SupportReply`, with the link to `/support/{id}`; an internal note changes nothing else.
     */
    post: operations['postSupportMessage'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/support-requests/{id}/screenshot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The screenshot of the request `id`, as the PNG it was stored as. */
    get: operations['getSupportScreenshot'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * A page of the users, from the most recent sign-up: those whose address contains `q`,
     *     whatever its case, or whose id is `q`, and of `status`.
     */
    get: operations['listUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The user `id`: as listed, plus the language, the counts of the library, the product events
     *     of the last 30 days by name, the sessions and the support requests.
     */
    get: operations['getUser'];
    put?: never;
    post?: never;
    /**
     * Erases the account `id` as its owner's deletion does: its documents, then the account and
     *     everything it had. The audit log keeps its id and the reason, never its address.
     */
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/users/{id}/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The data of the account `id`: the zip of `GET /api/v1/account/export`. */
    get: operations['exportUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/users/{id}/reactivate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reactivates the account `id`: it may sign in again. */
    post: operations['reactivateUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/v1/users/{id}/suspend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suspends the account `id`: it may not sign in, and its sessions end. */
    post: operations['suspendUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether the admin server's database answers within a second. */
    get: operations['healthz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Format: binary
     * @description A data export: a zip laid out like a local library, plus `account.json`.
     */
    AccountExport: string;
    /** @description The server's environment and version. */
    AdminEnvironment: {
      /** @description `local`, `staging` or `production`. */
      environment: string;
      /** @description The server's version. */
      version: string;
    };
    /** @description A session of the user, without its token. */
    AdminSession: {
      /**
       * Format: date-time
       * @description When it opened.
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description When it ends, unless it is seen again.
       */
      expiresAt: string;
      /**
       * Format: date-time
       * @description When it was last seen.
       */
      lastSeenAt: string;
    };
    /** @description What the app attached to a request. */
    AdminSupportContext: {
      /** @description The app's version. */
      appVersion: string;
      /** @description The interface's language code. */
      language: string;
      /** @description The app's platform: `web`, `android`… */
      platform: string;
      /** @description The route template of the screen the person was on. */
      screen: string;
    };
    /** @description A message of a request, internal notes included. */
    AdminSupportMessage: {
      /** @description The admin who wrote it; `null` for the person's messages. */
      adminId?: string | null;
      /** @description Who wrote it. */
      author: components['schemas']['SupportAuthor'];
      /** @description Its text. */
      body: string;
      /**
       * Format: date-time
       * @description When it was written.
       */
      createdAt: string;
      /**
       * Format: uuid
       * @description Its id.
       */
      id: string;
      /** @description Whether it is a note of the team the person never sees. */
      internal: boolean;
    };
    /** @description A request as the team sees it, without its messages. */
    AdminSupportRequest: {
      /**
       * Format: uuid
       * @description The account that sent it.
       */
      accountId: string;
      /**
       * Format: int64
       * @description How long ago it was sent, in seconds.
       */
      ageSeconds: number;
      /** @description The admin it is assigned to; `null` for nobody. */
      assignedTo?: string | null;
      /** @description What it is about. */
      category: components['schemas']['SupportCategory'];
      /**
       * Format: date-time
       * @description When it was sent.
       */
      createdAt: string;
      /** @description That account's address. */
      email: string;
      /**
       * Format: date-time
       * @description When the team first replied; `null` before.
       */
      firstResponseAt?: string | null;
      /** @description Whether a screenshot came with it. */
      hasScreenshot: boolean;
      /**
       * Format: uuid
       * @description Its id.
       */
      id: string;
      /**
       * Format: date-time
       * @description When it was resolved or closed, while it is.
       */
      resolvedAt?: string | null;
      /** @description Where it stands. */
      status: components['schemas']['SupportRequestStatus'];
      /**
       * Format: date-time
       * @description When its status last changed, or its author or the team last wrote.
       */
      updatedAt: string;
    };
    /** @description A request with its context and every message, oldest first, internal notes included. */
    AdminSupportThread: {
      /** @description What the app attached. */
      context: components['schemas']['AdminSupportContext'];
      /** @description Whether a screenshot came with it, served by `GET /support-requests/{id}/screenshot`. */
      hasScreenshot: boolean;
      /** @description Its messages: the first is the request's own. */
      messages: components['schemas']['AdminSupportMessage'][];
      /** @description The request, with its age. */
      request: components['schemas']['AdminSupportRequest'];
    };
    /** @description A user as the search lists them. */
    AdminUser: {
      /**
       * Format: date-time
       * @description When it signed up.
       */
      createdAt: string;
      /** @description Its address. */
      email: string;
      /** @description Whether the address is verified. */
      emailVerified: boolean;
      /**
       * Format: uuid
       * @description The account's id.
       */
      id: string;
      /**
       * Format: date-time
       * @description When one of its sessions was last seen; `null` without a session.
       */
      lastSeenAt?: string | null;
      /** @description Its plan. */
      plan: string;
      /** @description Whether it may sign in. */
      status: components['schemas']['AdminUserStatus'];
      /**
       * Format: int64
       * @description The bytes of its documents.
       */
      storageUsedBytes: number;
    };
    /**
     * @description A user in detail: as listed, plus the language, the counts of the library, the product
     *     events of the last 30 days by name, the sessions and the support requests.
     */
    AdminUserDetail: {
      /**
       * Format: int64
       * @description How many animations it has.
       */
      animationCount: number;
      /**
       * Format: date-time
       * @description When it signed up.
       */
      createdAt: string;
      /** @description Its address. */
      email: string;
      /** @description Whether the address is verified. */
      emailVerified: boolean;
      /** @description Its product events of the last 30 days, by name. */
      events: components['schemas']['EventCountBody'][];
      /**
       * Format: uuid
       * @description The account's id.
       */
      id: string;
      /** @description The language of its interface and emails. */
      language: string;
      /**
       * Format: date-time
       * @description When one of its sessions was last seen; `null` without a session.
       */
      lastSeenAt?: string | null;
      /** @description Its plan. */
      plan: string;
      /**
       * Format: int64
       * @description How many projects it has.
       */
      projectCount: number;
      /** @description Its sessions, the most recently seen first. */
      sessions: components['schemas']['AdminSession'][];
      /** @description Whether it may sign in. */
      status: components['schemas']['AdminUserStatus'];
      /**
       * Format: int64
       * @description The bytes of its documents.
       */
      storageUsedBytes: number;
      /** @description Its support requests, the most recently updated first. */
      supportRequests: components['schemas']['SupportRequestSummary'][];
    };
    /**
     * @description Whether an account may sign in.
     * @enum {string}
     */
    AdminUserStatus: 'active' | 'suspended';
    /** @description A firing alert. */
    Alert: {
      /** @description The `description` annotation. */
      description?: string | null;
      /** @description Alertmanager's fingerprint. */
      fingerprint: string;
      /** @description Every label. */
      labels: {
        [key: string]: string;
      };
      /** @description `alertname`. */
      name: string;
      /** @description `severity`, when set. */
      severity?: string | null;
      /** @description When it started firing, in RFC 3339. */
      startsAt: string;
      /** @description `active`, `suppressed` or `unprocessed`. */
      state: string;
      /** @description The `summary` annotation. */
      summary?: string | null;
    };
    /** @description The firing alerts of an environment, newest first. */
    Alerts: {
      /** @description The alerts. */
      alerts: components['schemas']['Alert'][];
    };
    /** @description An entry of the audit log: who did what, to what, when, why, and the state before and after. */
    AuditEntryBody: {
      /**
       * @description What they did: `user.suspend`, `user.reactivate`, `user.export`, `user.delete`,
       *     `support.update`, `support.reply` or `support.note`.
       */
      action: string;
      /** @description The admin's address. */
      adminEmail: string;
      /** @description The admin's id. */
      adminId: string;
      /** @description The state after the action. */
      after?: Record<string, never> | null;
      /**
       * Format: date-time
       * @description When.
       */
      at: string;
      /** @description The state before the action. */
      before?: Record<string, never> | null;
      /**
       * Format: int64
       * @description Its id: later entries have larger ones.
       */
      id: number;
      /** @description Why, for the actions on an account. */
      reason?: string | null;
      /** @description The target's id. */
      targetId: string;
      /** @description The kind of target: `user` or `support_request`. */
      targetType: string;
    };
    /** @description The admin signed in. */
    ConsoleAdmin: {
      /** @description The admin's address. */
      email: string;
      /**
       * Format: uuid
       * @description The admin's id.
       */
      id: string;
    };
    /**
     * @description A live session: who is signed in, the token every unsafe request sends in `X-CSRF-Token`,
     *     the environment this console administers and those its monitoring shows.
     */
    ConsoleSession: {
      /** @description The admin signed in. */
      admin: components['schemas']['ConsoleAdmin'];
      /** @description The session's CSRF token. */
      csrfToken: string;
      /** @description `LPA_ENVIRONMENT`: `local`, `staging` or `production`. */
      environment: string;
      /** @description `LPA_ENVIRONMENTS`: the environments the monitoring routes take as `env`. */
      monitoredEnvironments: string[];
    };
    /** @description A count of one day, week or month, named by its first day. */
    DayCountBody: {
      /**
       * Format: int64
       * @description How many.
       */
      count: number;
      /**
       * Format: date-time
       * @description Its first day, at midnight UTC.
       */
      day: string;
    };
    /** @description How many product events of one name. */
    EventCountBody: {
      /**
       * Format: int64
       * @description How many.
       */
      count: number;
      /** @description The event's name. */
      name: string;
    };
    /** @description How many exports of one format from one source. */
    ExportCountBody: {
      /**
       * Format: int64
       * @description How many.
       */
      count: number;
      /** @description `wasm`, `gif`, `apng`, `sprite_sheet` or `png_frames`. */
      format: string;
      /** @description `app` or `mcp`. */
      source: string;
    };
    /** @description A link to Grafana. */
    GrafanaLink: {
      /** @description Grafana Explore, split between the request's logs and its trace. */
      url: string;
    };
    /** @description The admin server's health. */
    Health: {
      /** @description Always `ok`: an admin server that cannot answer sends a problem. */
      status: components['schemas']['HealthStatus'];
    };
    /**
     * @description The status of a healthy admin server.
     * @enum {string}
     */
    HealthStatus: 'ok';
    /**
     * @description A log level the console filters by.
     * @enum {string}
     */
    LogLevel: 'error' | 'warn' | 'info' | 'debug' | 'trace';
    /** @description One log line. */
    LogLine: {
      /** @description Its other fields. */
      fields: {
        [key: string]: string;
      };
      /** @description Its level, when it has one. */
      level?: string | null;
      /** @description Its message. */
      message: string;
      /** @description The request it belongs to, when it names one. */
      requestId?: string | null;
      /** @description When, in RFC 3339. */
      time: string;
    };
    /** @description Log lines, newest first. */
    LogLines: {
      /** @description The lines, `limit` at most. */
      lines: components['schemas']['LogLine'][];
    };
    /** @description A message of the team: a reply the person is emailed about, or an internal note. */
    MessagePost: {
      /** @description Its text: 1 to 5,000 characters once trimmed. */
      body: string;
      /** @description Whether it is a note the person never sees, rather than a reply. */
      internal: boolean;
    };
    /** @description The overview of an environment. */
    Overview: {
      /** @description The environment. */
      environment: string;
      /**
       * Format: int64
       * @description The range's start, in Unix seconds.
       */
      from: number;
      /** @description The tiles: `up`, `errors`, `latency`, `requests`, `exports`, `mcp`, `storage`. */
      tiles: components['schemas']['Tile'][];
      /**
       * Format: int64
       * @description The range's end, in Unix seconds.
       */
      to: number;
    };
    /** @description A page of a list, from the most recently updated item. */
    Page_AdminSupportRequest: {
      /** @description The items. */
      items: {
        /**
         * Format: uuid
         * @description The account that sent it.
         */
        accountId: string;
        /**
         * Format: int64
         * @description How long ago it was sent, in seconds.
         */
        ageSeconds: number;
        /** @description The admin it is assigned to; `null` for nobody. */
        assignedTo?: string | null;
        /** @description What it is about. */
        category: components['schemas']['SupportCategory'];
        /**
         * Format: date-time
         * @description When it was sent.
         */
        createdAt: string;
        /** @description That account's address. */
        email: string;
        /**
         * Format: date-time
         * @description When the team first replied; `null` before.
         */
        firstResponseAt?: string | null;
        /** @description Whether a screenshot came with it. */
        hasScreenshot: boolean;
        /**
         * Format: uuid
         * @description Its id.
         */
        id: string;
        /**
         * Format: date-time
         * @description When it was resolved or closed, while it is.
         */
        resolvedAt?: string | null;
        /** @description Where it stands. */
        status: components['schemas']['SupportRequestStatus'];
        /**
         * Format: date-time
         * @description When its status last changed, or its author or the team last wrote.
         */
        updatedAt: string;
      }[];
      /** @description The `cursor` of the next page; `null` on the last one. */
      nextCursor?: string | null;
    };
    /** @description A page of a list, from the most recently updated item. */
    Page_AdminUser: {
      /** @description The items. */
      items: {
        /**
         * Format: date-time
         * @description When it signed up.
         */
        createdAt: string;
        /** @description Its address. */
        email: string;
        /** @description Whether the address is verified. */
        emailVerified: boolean;
        /**
         * Format: uuid
         * @description The account's id.
         */
        id: string;
        /**
         * Format: date-time
         * @description When one of its sessions was last seen; `null` without a session.
         */
        lastSeenAt?: string | null;
        /** @description Its plan. */
        plan: string;
        /** @description Whether it may sign in. */
        status: components['schemas']['AdminUserStatus'];
        /**
         * Format: int64
         * @description The bytes of its documents.
         */
        storageUsedBytes: number;
      }[];
      /** @description The `cursor` of the next page; `null` on the last one. */
      nextCursor?: string | null;
    };
    /** @description A page of a list, from the most recently updated item. */
    Page_AuditEntryBody: {
      /** @description The items. */
      items: {
        /**
         * @description What they did: `user.suspend`, `user.reactivate`, `user.export`, `user.delete`,
         *     `support.update`, `support.reply` or `support.note`.
         */
        action: string;
        /** @description The admin's address. */
        adminEmail: string;
        /** @description The admin's id. */
        adminId: string;
        /** @description The state after the action. */
        after?: Record<string, never> | null;
        /**
         * Format: date-time
         * @description When.
         */
        at: string;
        /** @description The state before the action. */
        before?: Record<string, never> | null;
        /**
         * Format: int64
         * @description Its id: later entries have larger ones.
         */
        id: number;
        /** @description Why, for the actions on an account. */
        reason?: string | null;
        /** @description The target's id. */
        targetId: string;
        /** @description The kind of target: `user` or `support_request`. */
        targetType: string;
      }[];
      /** @description The `cursor` of the next page; `null` on the last one. */
      nextCursor?: string | null;
    };
    /**
     * @description A panel of the monitoring views.
     * @enum {string}
     */
    Panel:
      | 'up'
      | 'requests'
      | 'errors'
      | 'latency'
      | 'slow_routes'
      | 'exports'
      | 'mcp'
      | 'auth'
      | 'storage'
      | 'quota'
      | 'memory'
      | 'cpu';
    /** @description A panel's series over the range, and the previous period's, moved onto the range. */
    PanelSeries: {
      /** @description The environment. */
      environment: string;
      /**
       * Format: int64
       * @description The range's start, in Unix seconds.
       */
      from: number;
      /** @description The panel. */
      panel: components['schemas']['Panel'];
      /** @description The previous period's series, their times moved forward by the range's length. */
      previous: components['schemas']['Series'][];
      /** @description The series. */
      series: components['schemas']['Series'][];
      /**
       * Format: int64
       * @description Seconds between two points.
       */
      stepSeconds: number;
      /**
       * Format: int64
       * @description The range's end, in Unix seconds.
       */
      to: number;
    };
    /**
     * @description An error, as RFC 9457 problem details with a stable code and its parameters, never a
     *     sentence: the interface translates `errors.<code>`.
     * @example {
     *       "code": "admin.invalid_credentials",
     *       "params": {},
     *       "status": 401,
     *       "type": "urn:life-pixel:problem:admin.invalid_credentials"
     *     }
     */
    Problem: {
      /** @description The stable code, dot-separated `snake_case` segments, domain first. */
      code: string;
      /** @description The parameters of the code's message, with camelCase keys. */
      params: {
        [key: string]: unknown;
      };
      /**
       * Format: int32
       * @description The HTTP status.
       */
      status: number;
      /** @description `urn:life-pixel:problem:<code>`. */
      type: string;
    };
    /** @description H13's aggregates over the period. */
    ProductAggregatesBody: {
      /**
       * Format: int64
       * @description The accounts whose first export falls in the period.
       */
      activatedAccounts: number;
      /** @description The active accounts of each day. */
      activePerDay: components['schemas']['DayCountBody'][];
      /** @description The active accounts of each month. */
      activePerMonth: components['schemas']['DayCountBody'][];
      /** @description The active accounts of each week. */
      activePerWeek: components['schemas']['DayCountBody'][];
      /** @description The exports by format and source. */
      exports: components['schemas']['ExportCountBody'][];
      /** @description The MCP calls by tool and outcome. */
      mcpCalls: components['schemas']['ToolCountBody'][];
      /** @description The sign-ups of each day. */
      signupsPerDay: components['schemas']['DayCountBody'][];
      /** @description The accounts by class of storage used, now. */
      storage: components['schemas']['SizeClassCountBody'][];
    };
    /** @description The product metrics of a period. */
    ProductMetricsBody: {
      /**
       * Format: date-time
       * @description The period's start, included.
       */
      from: string;
      /** @description H13's aggregates over it. */
      product: components['schemas']['ProductAggregatesBody'];
      /** @description The support queue's measures. */
      support: components['schemas']['SupportMetricsBody'];
      /**
       * Format: date-time
       * @description The period's end, excluded.
       */
      to: string;
    };
    /** @description Why an admin acts on an account: kept in the audit log. */
    ReasonBody: {
      /** @description The reason: 1 to 1,000 characters once trimmed. */
      reason: string;
    };
    /** @description A change of a request: its status, its assignee, or both. */
    RequestPatch: {
      /** @description The admin id it is assigned to; `null` for nobody. Absent, the assignee stays. */
      assignedTo?: string | null;
      status?: components['schemas']['SupportRequestStatus'] | null;
    };
    /**
     * Format: binary
     * @description A request's screenshot, as the PNG it was stored as.
     */
    Screenshot: string;
    /** @description One series of a panel, as uPlot draws it: its times and values side by side. */
    Series: {
      /** @description The series' labels, such as `route` or `format`. */
      labels: {
        [key: string]: string;
      };
      /** @description The query's name: the panel's, or `p50`, `p95`, `p99`. */
      name: string;
      /** @description Unix seconds. */
      times: number[];
      /** @description The value at each time; `null` where there is none. */
      values: (number | null)[];
    };
    /** @description What signing in sends. */
    SignInRequest: {
      /** @description The current code of the admin's authenticator: six digits. */
      code: string;
      /** @description The admin's address. */
      email: string;
      /** @description The password. */
      password: string;
    };
    /** @description How many accounts in one class of storage used. */
    SizeClassCountBody: {
      /**
       * Format: int64
       * @description How many accounts.
       */
      count: number;
      /** @description `lt_1k`, `lt_10k`, `lt_100k`, `lt_1m` or `ge_1m`. */
      sizeClass: string;
    };
    /** @description How many open requests of one status. */
    StatusCountBody: {
      /**
       * Format: int64
       * @description How many requests.
       */
      count: number;
      /** @description The status: `new`, `in_progress` or `waiting_for_user`. */
      status: components['schemas']['SupportRequestStatus'];
    };
    /**
     * @description Who wrote a message.
     * @enum {string}
     */
    SupportAuthor: 'user' | 'team';
    /**
     * @description What a support request is about.
     * @enum {string}
     */
    SupportCategory: 'bug' | 'account' | 'billing' | 'data_protection' | 'abuse' | 'other';
    /** @description The support queue's measures. */
    SupportMetricsBody: {
      /**
       * Format: double
       * @description The median age of the open requests now, in seconds; `null` without one.
       */
      medianAgeSeconds?: number | null;
      /**
       * Format: double
       * @description The median time to a first answer of the requests first answered over the period, in
       *     seconds; `null` without one.
       */
      medianFirstResponseSeconds?: number | null;
      /**
       * Format: double
       * @description The median time to resolution of the requests resolved over the period, in seconds;
       *     `null` without one.
       */
      medianResolutionSeconds?: number | null;
      /** @description The open requests by status, now. */
      openByStatus: components['schemas']['StatusCountBody'][];
    };
    /**
     * @description Where a support request stands.
     * @enum {string}
     */
    SupportRequestStatus: 'new' | 'in_progress' | 'waiting_for_user' | 'resolved' | 'closed';
    /** @description A request of the account, without its messages. */
    SupportRequestSummary: {
      /** @description What it is about. */
      category: components['schemas']['SupportCategory'];
      /**
       * Format: date-time
       * @description When it was sent.
       */
      createdAt: string;
      /** @description Whether a screenshot came with it; the screenshot itself is never served back. */
      hasScreenshot: boolean;
      /**
       * Format: uuid
       * @description Its id.
       */
      id: string;
      /** @description Where it stands. */
      status: components['schemas']['SupportRequestStatus'];
      /**
       * Format: date-time
       * @description When it last changed.
       */
      updatedAt: string;
    };
    /**
     * @description One tile of the overview: a panel's value at the end of the range, and at the end of the
     *     previous one; `null` when there is no data.
     */
    Tile: {
      /** @description The panel. */
      panel: components['schemas']['Panel'];
      /**
       * Format: double
       * @description Its value one range earlier.
       */
      previous?: number | null;
      /**
       * Format: double
       * @description Its value: the sum of its series; `latency` is p95.
       */
      value?: number | null;
    };
    /** @description How many MCP calls of one tool with one outcome. */
    ToolCountBody: {
      /**
       * Format: int64
       * @description How many.
       */
      count: number;
      /** @description `ok` or `error`. */
      outcome: string;
      /** @description The tool's name. */
      tool: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAlerts: {
    parameters: {
      query: {
        /** @description One of `LPA_ENVIRONMENTS`. */
        env: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The alerts, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Alerts'];
        };
      };
      /** @description `request.malformed` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.unavailable` */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.not_configured` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listAuditLog: {
    parameters: {
      query?: {
        /** @description Only the entries of this admin id. */
        adminId?: string;
        /** @description Only this action. */
        action?: string;
        /** @description Only the entries about this target id. */
        targetId?: string;
        /** @description The `nextCursor` of the previous page; none for the first. */
        cursor?: string;
        /** @description The most items of the page: 1 to 100, 50 by default. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of the log */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AuditEntryBody'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The live session */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsoleSession'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInRequest'];
      };
    };
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsoleSession'];
        };
      };
      /** @description `request.malformed` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.invalid_credentials` */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.csrf`: another origin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `rate_limit.exceeded`: 5 attempts a minute per address and per email */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  signOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `admin.csrf` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getGrafanaLink: {
    parameters: {
      query: {
        /** @description One of `LPA_ENVIRONMENTS`. */
        env: string;
        /** @description The request's id, as its log lines carry it. */
        requestId: string;
        /** @description As the overview's. */
        from?: string;
        /** @description As the overview's. */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The link */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GrafanaLink'];
        };
      };
      /** @description `request.malformed` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.not_configured` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getLogs: {
    parameters: {
      query: {
        /** @description One of `LPA_ENVIRONMENTS`. */
        env: string;
        /** @description Only this level, whatever its case. */
        level?: components['schemas']['LogLevel'];
        /** @description Only lines holding this text, as one phrase. */
        q?: string;
        /** @description As the overview's. */
        from?: string;
        /** @description As the overview's. */
        to?: string;
        /** @description The newest lines to return: 100 when absent, 500 at most. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The lines, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogLines'];
        };
      };
      /** @description `request.malformed` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.unavailable` */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.not_configured` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getProductMetrics: {
    parameters: {
      query?: {
        /** @description The period's start, included, in RFC 3339; 30 days before its end by default. */
        from?: string;
        /** @description The period's end, excluded, in RFC 3339; now by default. */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The metrics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductMetricsBody'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getOverview: {
    parameters: {
      query: {
        /** @description One of `LPA_ENVIRONMENTS`. */
        env: string;
        /** @description `now`, `now-<n><unit>` (`s`, `m`, `h`, `d`, `w`), Unix seconds or RFC 3339; `now-24h`. */
        from?: string;
        /** @description The same forms; `now`. At most 90 days after `from`. */
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The tiles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Overview'];
        };
      };
      /** @description `request.malformed`: an unknown environment or an invalid range */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.unavailable` */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.not_configured` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getPanelSeries: {
    parameters: {
      query: {
        /** @description One of `LPA_ENVIRONMENTS`. */
        env: string;
        /** @description The panel. */
        panel: components['schemas']['Panel'];
        /** @description As the overview's. */
        from?: string;
        /** @description As the overview's. */
        to?: string;
        /**
         * @description Seconds, or `<n><unit>`, between two points; 200 points when absent, 1,000 at most,
         *     15 seconds at least.
         */
        step?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The series */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PanelSeries'];
        };
      };
      /** @description `request.malformed` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.unavailable` */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `monitoring.not_configured` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listSupportRequests: {
    parameters: {
      query?: {
        /** @description Only the requests of this status. */
        status?: components['schemas']['SupportRequestStatus'];
        /** @description Only the requests of this category. */
        category?: components['schemas']['SupportCategory'];
        /** @description Only the requests assigned to this admin id. */
        assignee?: string;
        /** @description The `nextCursor` of the previous page; none for the first. */
        cursor?: string;
        /** @description The most items of the page: 1 to 100, 50 by default. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of the queue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AdminSupportRequest'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getSupportRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The request's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request and its thread */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSupportThread'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `support.request_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateSupportRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The request's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestPatch'];
      };
    };
    responses: {
      /** @description The request after the change */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSupportRequest'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.csrf`: another origin, or no valid `X-CSRF-Token` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `support.request_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  postSupportMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The request's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MessagePost'];
      };
    };
    responses: {
      /** @description The message */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSupportMessage'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.csrf`: another origin, or no valid `X-CSRF-Token` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `support.request_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `support.message_length`, with `min` and `max` */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getSupportScreenshot: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The request's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The PNG */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/png': components['schemas']['Screenshot'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `support.request_not_found`, `admin.screenshot_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: {
        /** @description Part of the address, whatever its case, or the whole account id. */
        q?: string;
        /** @description Only the users of this status. */
        status?: components['schemas']['AdminUserStatus'];
        /** @description The `nextCursor` of the previous page; none for the first. */
        cursor?: string;
        /** @description The most items of the page: 1 to 100, 50 by default. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of the users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AdminUser'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The account's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserDetail'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.user_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The account's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReasonBody'];
      };
    };
    responses: {
      /** @description Erased */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.csrf`: another origin, or no valid `X-CSRF-Token` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.user_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.reason_length`, with `min` and `max` */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  exportUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The account's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The zip, as an attachment named `life-pixel-export-<YYYY-MM-DD>.zip` */
      200: {
        headers: {
          /** @description The file's name */
          'Content-Disposition'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/zip': components['schemas']['AccountExport'];
        };
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.user_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  reactivateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The account's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReasonBody'];
      };
    };
    responses: {
      /** @description Reactivated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.csrf`: another origin, or no valid `X-CSRF-Token` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.user_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.reason_length`, with `min` and `max` */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  suspendUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The account's id */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReasonBody'];
      };
    };
    responses: {
      /** @description Suspended */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `request.malformed`: a cursor, an id, a query or a body that does not parse */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.unauthenticated`: no live session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.csrf`: another origin, or no valid `X-CSRF-Token` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.user_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description `admin.reason_length`, with `min` and `max` */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The database answers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description The database does not answer: `service.unavailable` */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
